### ISSUE TITLE
Avoiding LCD corruption?

### ISSUE THREAD

**Issue by domb84** [Dublerq/rpi-lcd-menu#10]
I've added a message(autoscroll=True) option to this fork.

https://github.com/domb84/rpi-lcd-menu

However, if I render a menu while the scrolling occurs the screen gets corrupted. Do you know of a way to avoid this?

**Comment by domb84** [comment]
Fixed this in my build by using a queue

**Comment by theophile** [comment]
@domb84 , hey! I'm working off of your fork but since I can't open an issue there I'm hoping you'll see this and reply. I started out using Dublerq's main repo to try to work out a menu system for a MIDI synth project and made my way through the "example" scripts until I ran into the same problem you were having with submenus. So I was excited to find your fork, as it looks like you've addressed the submenus issue!

However, I'm having some trouble figuring out how to properly create a submenu. For instance, the "example3.py" script runs as expected out of the main repo, but on your fork, I get this error:
```
Traceback (most recent call last):
  File "example3.py", line 51, in <module>
    main()
  File "example3.py", line 18, in main
    submenu = RpiLCDSubMenu(menu)
  File "/home/theophile/rpi-lcd-menu-fixed/examples/rpilcdmenu/rpi_lcd_submenu.py", line 9, in __init__
    self.lcd = base_menu.lcd
AttributeError: 'RpiLCDMenu' object has no attribute 'lcd'
```
What changes would be necessary to "example3.py" to get it to run as expected on your fork? Thanks!

**Comment by domb84** [comment]
I can’t say I’ve tested with the examples in a long time, but I use sub menus extensively in my project without issues. Paste in your full example and I’ll take a look if I get a chance.

**Comment by theophile** [comment]
Thanks @domb84 ! I've pasted below the code from the example3.py I'm trying to get working. The only change from the "stock" example3.py file is that I've also merged the changes from @pierremtb 's branch [here](https://github.com/pierremtb/rpi-lcd-menu), which allow the use of i2c backpack LCDs rather than communicating over GPIO, so the `menu = RpiLCDMenu()` line on line 12 doesn't have the GPIO pin information. For reference, I'll also paste below the full rpi_lcd_menu.py file I'm using. Thanks for any help you can provide!

**example3.py**
```
#!/usr/bin/python

"""
multi level menu
"""

from rpilcdmenu import *
from rpilcdmenu.items import *


def main():
    menu = RpiLCDMenu()

    function_item1 = FunctionItem("Item 1", fooFunction, [1])
    function_item2 = FunctionItem("Item 2", fooFunction, [2])
    menu.append_item(function_item1).append_item(function_item2)

    submenu = RpiLCDSubMenu(menu)
    submenu_item = SubmenuItem("SubMenu (3)", submenu, menu)
    menu.append_item(submenu_item)

    submenu.append_item(FunctionItem("Item 31", fooFunction, [31])).append_item(
        FunctionItem("Item 32", fooFunction, [32]))
    submenu.append_item(FunctionItem("Back", exitSubMenu, [submenu]))

    menu.append_item(FunctionItem("Item 4", fooFunction, [4]))

    menu.start()
    menu.debug()
    print("----")
    # press first menu item and scroll down to third one
    menu.processEnter().processDown().processDown()
    # enter submenu, press Item 32, press Back button
    menu.processEnter().processDown().processEnter().processDown().processEnter()
    # press item4 back in the menu
    menu.processDown().processEnter()


def fooFunction(item_index):
    """
        sample method with a parameter
        """
    print("item %d pressed" % (item_index))


def exitSubMenu(submenu):
    return submenu.exit()


if __name__ == "__main__":
    main()
```

**rpi_lcd_menu.py**
```
import queue
import threading
from time import sleep

from rpilcdmenu.base_menu import BaseMenu
from rpilcdmenu.rpi_lcd_hwd import RpiLCDHwd


class RpiLCDMenu(BaseMenu):
    def __init__(self, scrolling_menu=False):
        """
        Initialize menu
        """
        self.lcd_queue = queue.Queue(maxsize=0)
        self.scrolling_menu = scrolling_menu

        # turn-on the worker thread
        threading.Thread(target=self.lcd_queue_processor).start()

        super(self.__class__, self).__init__()

    def clearDisplay(self):
        """
        Clear LCD Screen
        """
        self.lcd.write4bits(RpiLCDHwd.LCD_CLEARDISPLAY)  # command to clear display
        self.lcd.delayMicroseconds(3000)  # 3000 microsecond sleep, clearing the display takes a long time

        return self

    def lcd_render(self, render_text):
        i = 0
        lines = 0

        # return home rather thanclear the display
        self.lcd.write4bits(RpiLCDHwd.LCD_RETURNHOME)

        for char in render_text:
            if char == '\n':
                self.lcd.write4bits(0xC0)  # next line
                i = 0
                lines += 1
            else:
                self.lcd.write4bits(ord(char), True)
                i = i + 1

            if i == 16:
                self.lcd.write4bits(0xC0)  # last char of the line

    def message(self, text, autoscroll=False):
        """ Send long string to LCD. Long single line messages are split and scrolled if autoscroll is set.
        else the are split and cropped."""

        # clear the existing lcd queue
        with self.lcd_queue.mutex:
            self.lcd_queue.queue.clear()

        try:
            splitlines = text.split('\n')

            # process a single line
            if len(splitlines) < 2:
                line1 = splitlines[0]

                # if there's one line and its longer than 16 characters, split it onto line 2
                len1 = len(line1)
                if len1 > 16:
                    #  // will return an integer
                    half = (len1 // 2)
                    # split it in half
                    line2 = line1[half:]
                    line1 = line1[0:half]
                else:
                    #  line 2 is nothing if line1 is not more than 16 characters
                    line2 = ''

                # recalculate lengths for srcoller
                len1 = len(line1)
                len2 = len(line2)
                final_text = ("%s\n%s" % (line1, line2))

            # process 2 lines
            elif len(splitlines) == 2:
                # set lengths for scroller but other wise leave the text
                len1 = len(splitlines[0])
                len2 = len(splitlines[1])
                # pad out short lines
                line1 = "{:<16}".format(splitlines[0])
                line2 = "{:<16}".format(splitlines[1])
                final_text = ("%s\n%s" % (line1, line2))

            else:
                # TODO process more than 2 lines. Currently they just get cropped.
                len1 = len(splitlines[0])
                len2 = len(splitlines[1])
                # pad out short lines
                line1 = "{:<16}".format(splitlines[0])
                line2 = "{:<16}".format(splitlines[1])
                final_text = ("%s\n%s" % (line1, line2))

            # TODO needs to be interruptable somehow
            if autoscroll == True:
                # add one to the longest length so it scrolls off screen
                if len1 < len2:
                    text_length = len2
                else:
                    text_length = len1

                # render for 16x2
                fixed_text = self.render_16x2(final_text)
                # render the output
                self.lcd_queue.put((self.lcd_render, fixed_text))

                # only scroll if needed
                if text_length > 16:

                    # add one to the longest length so it scrolls off screen
                    text_length = text_length + 1

                    # show the text for one second
                    sleep(1)

                    # scroll the message right to left
                    # start 1 character in as we've already rendered the first character
                    for index in range(1, text_length):
                        # render at 16x2
                        fixed_text = self.render_16x2(final_text, index)

                        # render the output
                        self.lcd_queue.put((self.lcd_render, fixed_text))

                    # scroll the rest of the way
                    for index in range(0, 16):
                        # render at 16x2
                        fixed_text = self.render_16x2_reverse(final_text, index)

                        # render the output
                        self.lcd_queue.put((self.lcd_render, fixed_text))

                    # render for 16x2
                    fixed_text = self.render_16x2(final_text)

                    # render the output
                    self.lcd_queue.put((self.lcd_render, fixed_text))

                return self

            else:
                # just show the text if theres no autoscroll
                fixed_text = self.render_16x2(final_text)

                # render the output
                self.lcd_queue.put((self.lcd_render, fixed_text))

                return self


        except Exception as e:
            print("Autoscroll error: %s" % e)

    def displayTestScreen(self):
        """
        Display test screen to see if your LCD screen is wokring
        """
        self.message('Hum. body 36,6\xDFC\nThis is test')

        return self

    def render(self):
        """
        Render menu
        """
        if len(self.items) == 0:
            self.message('Menu is empty')
            return self
        elif len(self.items) <= 2:
            options = (self.current_option == 0 and ">" or " ") + self.items[0].text
            if len(self.items) == 2:
                options += "\n" + (self.current_option == 1 and ">" or " ") + self.items[1].text
            # print(options)
            if self.scrolling_menu == True:
                self.message(options, autoscroll=True)
            else:
                self.message(options)
            return self

        options = ">" + self.items[self.current_option].text

        if self.current_option + 1 < len(self.items):
            options += "\n " + self.items[self.current_option + 1].text
        else:
            options += "\n " + self.items[0].text

        if self.scrolling_menu == True:
            self.message(options, autoscroll=True)
        else:
            self.message(options)

        return self

    def render_16x2(self, text, index=0):

        # incoming text will already have been cleaned up and split with a line break
        # by the message function
        try:
            # render incoming text as 16x2 by taking the starting index and adding 16
            # for each line
            lines = text.split('\n')
            line1 = lines[0]
            line2 = lines[1]

            # render from index to 16 characters in
            last_char = index + 16

            # # pad out the text if its less than 16 characters  long
            line1_vfd = "{:<16}".format(line1[index:last_char])
            line2_vfd = "{:<16}".format(line2[index:last_char])

            return ("%s\n%s" % (line1_vfd, line2_vfd))


        except Exception as e:
            print("Render error: %s" % e)

    def render_16x2_reverse(self, text, index=0):

        # incoming text will already have been cleaned up and split with a line break
        # by the message function
        try:
            # render incoming text as 16x2 but right justified. ie add padding to the left.
            # only useful for the reverse scroll
            lines = text.split('\n')
            line1 = lines[0]
            line2 = lines[1]
            # pad out the text if its less than 16 characters long from the left
            line1_vfd = "{:>16}".format(line1[0:index])
            line2_vfd = "{:>16}".format(line2[0:index])

            return ("%s\n%s" % (line1_vfd, line2_vfd))


        except Exception as e:
            print("Render error: %s" % e)

    def lcd_queue_processor(self):

        self.lcd = RpiLCDHwd()
        self.lcd.initDisplay()

        # clear it once in case of existing corruption
        self.clearDisplay()

        # process the queue
        while True:
            items = self.lcd_queue.get()
            func = items[0]
            args = items[1:]
            func(*args)
```

**Comment by theophile** [comment]
Also @domb84 , in case it helps, I forked your repo and pushed the changes I made to incorporate the i2c implementation by @pierremtb. You can see the resulting changes here: https://github.com/theophile/rpi-lcd-menu/commit/ebd7285decf7d00f00eab2cb4c259516fc0c3c5f

**Comment by domb84** [comment]
Looks like you’ve found your issue and it’s something to do with the changes you’ve merged. I’ve only got gpio so wouldn’t be able to test.

**Comment by theophile** [comment]
Hi @domb84 , thanks so much for the follow-up. I checked and double-checked the i2c changes and couldn't figure out what, if anything, would produce this error, so to test I tried example3.py in a clean clone of your fork, no changes. It produces the same error:
```
Traceback (most recent call last):
  File "example3.py", line 51, in <module>
    main()
  File "example3.py", line 18, in main
    submenu = RpiLCDSubMenu(menu)
  File "/home/theophile/rpi-lcd-menu-domb84/examples/rpilcdmenu/rpi_lcd_submenu.py", line 9, in __init__
    self.lcd = base_menu.lcd
AttributeError: 'RpiLCDMenu' object has no attribute 'lcd'
```

To reproduce, simply clone your repo, go into "examples," and execute example3.py. I have to assume that the queuing system you came up with somehow affects the syntax for creating a submenu. Any ideas? I really appreciate your help!

**Comment by domb84** [comment]
Very strange. I can’t remember what example 3 is, but if it’s the one that allows you to scroll the text manually it may well not work as I’ve never used that function. I’m afraid I don’t have time or in all honesty the knowledge right now to dig into it. If I get a chance I’ll try but probably best to hack away at it for now or try to merge in my changes.

**Comment by domb84** [comment]
Here’s the project I use my fork in, might help. Have a look at the menu manager class.

https://github.com/domb84/teac_th300dab_rpi_streamer

**Comment by domb84** [comment]
> Hi @domb84 , thanks so much for the follow-up. I checked and double-checked the i2c changes and couldn't figure out what, if anything, would produce this error, so to test I tried example3.py in a clean clone of your fork, no changes. It produces the same error:
> 
> ```
> Traceback (most recent call last):
>   File "example3.py", line 51, in <module>
>     main()
>   File "example3.py", line 18, in main
>     submenu = RpiLCDSubMenu(menu)
>   File "/home/theophile/rpi-lcd-menu-domb84/examples/rpilcdmenu/rpi_lcd_submenu.py", line 9, in __init__
>     self.lcd = base_menu.lcd
> AttributeError: 'RpiLCDMenu' object has no attribute 'lcd'
> ```
> 
> To reproduce, simply clone your repo, go into "examples," and execute example3.py. I have to assume that the queuing system you came up with somehow affects the syntax for creating a submenu. Any ideas? I really appreciate your help!

i've confirmed that this is the case. I think it's something do to with the fact i've modified it around being called from a class rather than explicitly in the main thread. so i'm expecting self.lcd to exist, not just lcd.

Try calling it from a class.

**Comment by theophile** [comment]
Thanks so much @domb84! I took your advice and used your menu_manager.py to create a class, and tried calling it via the class, but I got the same error. Here's as much as I've been able to figure out:

- The error complains about [line 9 of rpi_lcd_submenu.py](https://github.com/domb84/rpi-lcd-menu/blob/d3566a8e7770b4eeb7c32db564457853d0c7e7d0/rpilcdmenu/rpi_lcd_submenu.py#L9), which seems to refer to `base_menu.lcd` from the main RpiLCDMenu class.
- The RpiLCDMenu class is defined in rpi_lcd_menu.py. In the original project, [line 11](https://github.com/Dublerq/rpi-lcd-menu/blob/188ff12a031469d58e7171e82161405fb113ba6a/rpilcdmenu/rpi_lcd_menu.py#L11) defined self.lcd in the __init__ function. I see that as part of implementing the queueing system, you moved that down to [line 252](https://github.com/domb84/rpi-lcd-menu/blob/640e4346fb4f065c0de1fd5fe17b4cb30a09b502/rpilcdmenu/rpi_lcd_menu.py#L252) as part of the new `lcd_queue_processor` function.
- For whatever reason, when a submenu is called, it looks like rpi_lcd_submenu.py tries to create a RpiLCDSubMenu as a subclass of RpiLCDMenu, but the RpiLCDMenu object isn't returning an "lcd" attribute from the `lcd_queue_processor` function.
- I can get past the error by commenting out [line 9 of rpi_lcd_submenu.py](https://github.com/domb84/rpi-lcd-menu/blob/d3566a8e7770b4eeb7c32db564457853d0c7e7d0/rpilcdmenu/rpi_lcd_submenu.py#L9), but then that breaks the rendering of the submenu because the RpiLCDSubMenu object needs the "lcd" object for the other inherited functions in rpi_lcd_menu.py to work.
- I looked through your Teac T-H300DAB project repo to see if you were using a different method to create/define the self.lcd object, but I couldn't find anything.

I feel like I only barely understand this so I could be way off, but it is possible that `lcd_queue_processor` might not be returning an "lcd" attribute for RpiLCDMenu for some reason?

**Comment by domb84** [comment]
I really don’t know I’m afraid. I’m really not a developer and I hack together what I can.

Curiously I’m having a different issue which could be related in some way, but I’m not sure when I’ll get time to look.

**Comment by domb84** [comment]
I think in your example you can just change self.lcd to lcd and it will work.

**Comment by domb84** [comment]
Actually I can’t think of a good reason that self.lcd has been moved down to the queue, so move that back to the main init.

**Comment by theophile** [comment]
It's funny, I tried that earlier and it did get me past that error, but then I was having the exact same issue you described in Issue #8, where once a submenu is rendered, any attempt to navigate through it just returns to the previous menu, and options cannot be selected from the submenu. I assumed that this was something you had addressed with the queueing, but now I think it's separate. For whatever it's worth, here's what I ended up doing to move past the "lcd" error: https://github.com/theophile/rpi-lcd-menu/commit/3f57717b917548d877adf38dc88c83242c1e1dd3

Now I'm digging through your commit history on your Teac T-H300DAB project in the hopes that somewhere in there you have an example of how you implemented this (https://github.com/Dublerq/rpi-lcd-menu/issues/8#issuecomment-751499097) to address the submenu navigation issue. It looks like this (https://github.com/domb84/teac_th300dab_rpi_streamer/blob/d2e92ede385e3b863391a1fc0b0c9ddf8fafe1a1/examples/main.py) may be the closest to where I'm at right now, but even that script seems to have the same submenu navigation problem. Any advice for how you fixed that?

**Comment by theophile** [comment]
Bam! Found the missing piece of the puzzle with a little help from @pierremtb's article here: https://medium.com/zero-to-product/building-a-kettle-manager-raspberry-pi-machine-learning-and-3d-printing-b42709bd3ee2 , and specifically this line here: https://gist.github.com/pierremtb/c7da94d6c7c1135b2672182e5deace68#file-display-py-L128

For some reason, adding `menu =` in front of the call to the `menu.processEnter()` function made the difference, and now submenu navigation is working as expected. Thanks again for your help @domb84 . And I hope you post a video of your Teac T-H300DAB project. It looks really slick!

**Comment by domb84** [comment]
Excellent! I think you may have actually resolved an edge case in my code as well where returning from a message was causing an issue.

**Comment by domb84** [comment]
Excellent! I think you may have actually resolved an edge case in my code as well where returning from a message was causing an issue.

**Comment by pierremtb** [comment]
Sorry I’m a bit late to the party. Happy to see the issue resolved!
