### ISSUE TITLE
AttributeError: 'RpiLCDMenu' object has no attribute 'GPIO' when running example3.py

### ISSUE THREAD

**Issue by rhaejr** [Dublerq/rpi-lcd-menu#3]
The `RpiLCDSubMenu` class calls `self.GPIO = base_menu.GPIO` but `RpiLCDMenu` doesn't seem to have a member variable called GPIO but it does have a GPIO parameter

**Comment by Dublerq** [comment]
#4

**Comment by Dublerq** [comment]
@rhaejr, thank you for your report. The issue has been fixed.
